### ISSUE TITLE
[SVT-AV1]Code fault tolerance does not work when there is a lack of space between parameters.

### ISSUE THREAD

**Issue by GuCaixuan** [AOMediaCodec/SVT-AV1#239]
Dear,
When we use the SVT-AV1 App with commitID bef6750 which is from Github Master to do encoding, we found that the code fault tolerance does not work when there is a lack of space between parameters.
Example for below command, app SvtAv1EncApp no error print.
SvtAv1EncApp -i Netflix_Crosswalk_3840x2160_10bit_60Hz_P420.yuv -w 4096 -h 2160 **-fps 60-bit-depth 10-rc 0-enc-mode 7** -intra-period 55 -n 100 -b ss-1q0.av1
`-------------------------------------------`
SVT-AV1 Encoder
SVT [version]:  SVT-AV1 Encoder Lib v0.4.0
SVT [build]  :  GCC 7.3.0        64 bit
LIB Build date: Apr 30 2019 16:28:14
`-------------------------------------------`
Number of logical cores available: 112
Number of PPCS 99
`-------------------------------------------`
SVT [config]: Main Profile      Tier (auto)     Level (auto)
SVT [config]: EncoderMode                                                       : 8
SVT [config]: EncoderBitDepth / EncoderColorFormat / CompressedTenBitFormat     : 8 / 1 / 0
SVT [config]: SourceWidth / SourceHeight                                        : 4096 / 2160
SVT [config]: FrameRate / Gop Size                                              : 60 / 56
SVT [config]: HierarchicalLevels / BaseLayerSwitchMode / PredStructure          : 4 / 0 / 2
SVT [config]: BRC Mode / QP  / LookaheadDistance / SceneChange                  : CQP / 50 / 33 / 0
`-------------------------------------------`
Encoding       100
SUMMARY --------------------------------- Channel 1  --------------------------------
Total Frames            Frame Rate              Byte Count              Bitrate
         100            60.00 fps                219536039              1053772.99 kbps

Channel 1
Average Speed:          5.136 fps
Total Encoding Time:    19471 ms
Total Execution Time:   49896 ms
Average Latency:        9820 ms
Max Latency:            11419 ms
Encoder finished

Thanks and waiting for your feedback.

**Comment by hassount** [comment]
@GuCaixuan Thank you, for reporting this. Definitely something that we'll need to fix asap

**Comment by hassount** [comment]
welcoming contributions here

**Comment by hassount** [comment]
i believe that this has been addressed, can we double check ? @GuCaixuan @OmranAbdelkafi

**Comment by GuCaixuan** [comment]
Hi, @hassount ,
     I double checked this issue on CommitID: ba72bc8, the issue is still **reproduces**.
     Command Line is:
./SvtAv1EncApp -i Netflix_Crosswalk_3840x2160_10bit_60Hz_P420.yuv -w 4096 -h 2160 **--fps 60-bit-depth 10-rc 0-enc-mode 7--keyint 55** -n 100 -b output.av1
<img width="675" alt="av1_239bug" src="https://user-images.githubusercontent.com/45022980/85087318-c6560080-b20f-11ea-8fd3-0df14ab15e6e.PNG">

**Comment by hassount** [comment]
@xuguangxin thank you for the test

**Comment by xuguangxin** [comment]
> @xuguangxin thank you for the test

@hassount , @GuCaixuan is the right person :)
